title: Shen Research Group
baseURL: https://jieshenlab-NTU.github.io/
theme: blox-bootstrap

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

enableGitInfo: false
summaryLength: 35
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
disableAliases: false

pagination:
  pagerSize: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON
    - WebAppManifest
  section:
    - HTML
    - RSS

imaging:
  resampleFilter: lanczos
  quality: 82
  anchor: smart

timeout: 600000

permalinks:
  authors: /author/:slug/
  tags: /tag/:slug/
  categories: /category/:slug/
  publication_types: /publication-type/:slug/

taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors

markup:
  _merge: deep
  goldmark:
    renderer:
      unsafe: true

related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70

security:
  _merge: deep

sitemap:
  _merge: deep
